version: '3.8'

services:
  lyt-vector-api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    container_name: lyt-vector-api-container
    volumes:
      - vector-store-data:/usr/src/app
    restart: unless-stopped
    env_file:
      - .env


volumes:
  vector-store-data:
    driver: local